services:
  - type: web
    name: pneumonia-detection-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT api.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: PORT
        value: 10000 